### ISSUE TITLE
Paragraph in ObservalbeObject is cut off

### ISSUE THREAD

**Issue by Mrxx99** [windows-toolkit/MVVM-Samples#30]
![image](https://user-images.githubusercontent.com/33566379/98982758-25e6dc80-2520-11eb-8f4f-c3136293570d.png)

This text goes on further in the markdown file but is cut off in the sample app.

**Comment by michael-hawker** [comment]
Thanks @Mrxx99 for the report!

@Sergio0694 is this a sample app issue or an issue in the toolkit itself?

**Comment by Sergio0694** [comment]
Nice catch, thanks @Mrxx99! @michael-hawker was just a small regex bug, fixed in the open PR 😊
