### ISSUE TITLE
Where is Nuget Package of Microsoft.Toolkit.Mvvm

### ISSUE THREAD

**Issue by RaoHammas** [windows-toolkit/MVVM-Samples#35]
Hey, I can't find nuget package of `Microsoft.Toolkit.Mvvm` the [link](https://github.com/windows-toolkit/MVVM-Samples/blob/master/docs/resources/images/ManageNugetPackages.png) in introduction is broken and also in visual studio it is not found. Where is it ?

**Comment by RaoHammas** [comment]
Sorry my bad forgot to enable prerelease lol

**Comment by SmRiley** [comment]
I am curious to ask, when will the official version be released?
