### ISSUE TITLE
UWP Sample

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/MVVM-Samples#4]

**Comment by dgellow** [comment]
Is it still a concern? As far as I can tell an UWP sample has already been added: https://github.com/windows-toolkit/MVVM-Samples/tree/master/samples/MvvmSampleUwp.

**Comment by michael-hawker** [comment]
Thanks @dgellow, I think we just forgot to close this when we shipped. Appreciate you letting us know!

We have to circle back on the Uno sample and some others still, just been a bit crazy since we shipped too... 🙂

FYI @Sergio0694
