### ISSUE TITLE
Best practice to propagate property changes to parent class

### ISSUE THREAD

**Issue by Gerardo-Sista** [windows-toolkit/MVVM-Samples#47]
Hello everyone,
I'm pretty new to this very promising MVVM toolkit, 
I wish to know if there's an already easy to use built in mechanism for propertychanged notification between classes. 
**Please provide a small example useful for everyone, expoecially for beginners like me**. 

Thank you in advance!

The scenario: 

```
//The "parent" class
public class Person: ObservableValidator
{
   private string _name;
   public string Name { get => _name; set { SetProperty(ref _name, value); } }

  private List<Address>  _addresses;
  public List<Address>  Addresses 
  { 
    get => _addresses; 
    set 
       { 
             SetProperty(ref _addresses, value);
                   
                   //I need here  to  call  a method  when **Address.IsDefault**  has changed in any Address of the list
        }
    }
//other properties here........
}


//The "child "class used as property (a List) in the parent class

public class Address: ObservableValidator
{
   private bool  _isDefault;
   public bool  IsDefault { 
     get => _isDefault; 
     set {
              SetProperty(ref _isDefault, value); 
             // I need here to notify the "parent" class (Person) that  _isDefault has changed
           } 
    }

  private string  _fullAddress;
  public string   FullAddress{ get => _fullAddress; set { SetProperty(ref _fullAddress, value); } }

//other properties here........
}

```

**Comment by mrlacey** [comment]
Look at using a [Messenger](https://github.com/windows-toolkit/MVVM-Samples/blob/master/docs/mvvm/Messenger.md) to communicate between classes

**Comment by Gerardo-Sista** [comment]
> Look at using a [Messenger](https://github.com/windows-toolkit/MVVM-Samples/blob/master/docs/mvvm/Messenger.md) to communicate between classes

Thank you  @mrlacey,
I've read the doc at the link you provided, but it would be great if you provide a very small two classes example because there are only code snippets describing how it works. I don't know how to implement in my scenario. Please take into consideration I'm a beginner so be patient: it would be useful also for other people.

**Comment by mrlacey** [comment]
There's an example at https://github.com/XamlBrewer/UWP-MVVM-Toolkit-Sample
where you can see messages being [sent](https://github.com/XamlBrewer/UWP-MVVM-Toolkit-Sample/blob/master/XamlBrewer.UWP.MvvmToolkit.Sample/ViewModels/ThemeModuleViewModel.cs#L52)
and [received](https://github.com/XamlBrewer/UWP-MVVM-Toolkit-Sample/blob/master/XamlBrewer.UWP.MvvmToolkit.Sample/ViewModels/ColorModuleViewModel.cs#L56).

**Comment by Gerardo-Sista** [comment]
@mrlacey thank you, this example is lot more clear. 
However, is really this the best practice to propagate Propertychanged from child to parent class?
Messaging looks to me more as a suitable way to communicate between viewmodels.

**Comment by mrlacey** [comment]
> @mrlacey thank you, this example is lot more clear.
> However, is really this the best practice to propagate Propertychanged from child to parent class?
> Messaging looks to me more as a suitable way to communicate between viewmodels.

I don't know a general "best practice" for communicating between parent and child classes.
If anything, the "best practice" is to avoid the need to do this.
If you do need to communicate between them there are two options: create a direct connection between them or an indirect connection. With a direct connection, the child will need a reference to its parent or the parent will subscribe to an event on each child. For an indirect connection, one (the child) will broadcast a message that the other (the parent) will receive.
As with many things MVVM, some people have some VERY strong opinions about the **right way** to do things. I suggest you use what is preferable to you and is consistent with the rest of your codebase.

**Comment by Gerardo-Sista** [comment]
@mrlacey  
I will explore all the options you suggested. 
Thank you for your support.
